services:
    mysql:
        image: mariadb
        command: --default-authentication=plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3307:3306

    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025

