#!/bin/bash

# Quick reference for MTAV development commands

echo "🚀 MTAV Development Quick Reference"
echo "=================================="
echo ""
echo "🎯 New Developer:"
echo "  ./mtav up                     # One command to build & start everything"
echo ""
echo "🔄 Daily Development:"
echo "  ./mtav up                     # Start development environment"
echo "  ./mtav stop                   # Stop containers (preserved for quick restart)"
echo "  ./mtav down                   # Stop and remove containers (clean shutdown)"
echo "  ./mtav build                  # Update dependencies"
echo "  ./mtav status                 # Show container status"
echo ""
echo "🛠️ Direct Tasks:"
echo "  .docker/scripts/artisan.sh migrate      # Run migrations"
echo "  .docker/scripts/artisan.sh tinker       # Laravel tinker"
echo "  .docker/scripts/composer.sh install     # Install PHP deps"
echo "  .docker/scripts/composer.sh require X   # Add PHP package"
echo "  .docker/scripts/npm.sh install          # Install JS deps"
echo "  .docker/scripts/npm.sh add vue@latest   # Add JS package"
echo "  .docker/scripts/db.sh                   # Access database"
echo "  .docker/scripts/shell.sh php            # Shell into container"
echo ""
echo "🌐 URLs:"
echo "  http://localhost:8080   # Main application"
echo "  http://localhost:5173   # Vite dev server"
echo "  http://localhost:8025   # MailHog (email testing)"
echo ""
echo "💡 Philosophy:"
echo "  Simple by default (./mtav), powerful when needed (.docker/scripts/)"